version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: table_reservations
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c "sleep 5 && 
            alembic upgrade head &&
            uvicorn app.main:app --host 0.0.0.0 --port ${WEB_PORT}"

volumes:
  postgres_data: