"""empty message

Revision ID: 95e8a9e06caa
Revises: 
Create Date: 2025-04-08 22:00:32.015207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95e8a9e06caa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('reservation_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('reservation_table_id_fkey', 'reservation', type_='foreignkey')
    op.drop_table('Table')
    op.drop_table('reservation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reservation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='reservation_duration_minutes_check'),
    sa.ForeignKeyConstraint(['table_id'], ['Table.id'], name='reservation_table_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reservation_pkey')
    )
    op.create_table('Table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.CheckConstraint('seats > 0', name='Table_seats_check'),
    sa.PrimaryKeyConstraint('id', name='Table_pkey')
    )
    op.drop_table('reservations')
    op.drop_table('tables')
    # ### end Alembic commands ###
